# I giocatori possono ferirsi e uccidersi tra di loro.
PVP=true

# PVP is logged to admin chat
PVPLogToolChat=true

# PVP is logged to file
PVPLogToolFile=true

# Il tempo della partita si ferma quando non ci sono giocatori nel server.
PauseEmpty=true

# Attiva o disattiva la chat globale.
GlobalChat=true

ChatStreams=s,r,a,w,y,sh,f,all

# I giocatori possono iscriversi senza avere già un account nella whitelist. Se impostato a false, gli amministratori devono creare manualmente le combinazioni nome utente/password.
Open=true

# Il primo messaggio di benvenuto visibile nel pannello della chat. Questo sarà visualizzato immediatamente dopo il login del giocatore. puoi usare i colori RGB per azzardare il colore del messaggio di benvenuto. Puoi anche usare <LINE> per creare linee separate all'interno del testo. Usa: <RGB:1,0,0> Questo messaggio apparirà rosso!
ServerWelcomeMessage=Welcome to Project Zomboid Multiplayer! <LINE> <LINE> To interact with the Chat panel: press Tab, T, or Enter. <LINE> <LINE> The Tab key will change the target stream of the message. <LINE> <LINE> Global Streams: /all <LINE> Local Streams: /say, /yell <LINE> Special Steams: /whisper, /safehouse, /faction. <LINE> <LINE> Press the Up arrow to cycle through your message history. Click the Gear icon to customize chat. <LINE> <LINE> Happy surviving!

# Aggiungere i nomi utente sconosciuti alla whitelist quando i giocatori si iscrivono. I giocatori forniranno il proprio nome utente/password al momento dell'iscrizione. (Questo è per i server Open=true)
AutoCreateUserInWhiteList=false

# Mostra il nome sopra la testa del giocatore.
DisplayUserName=true

# Mostra il nome e il cognome sopra le teste del giocatore.
ShowFirstAndLastName=false

UsernameDisguises=false

HideDisguisedUserName=false

SwitchZombiesOwnershipEachUpdate=false

# Forzare ogni nuovo giocatore a spawnare a queste coordinate mondiali x,y,z impostate. Trova le coordinate desiderate su map.projectzomboid.com. (Ignorato quando 0,0,0)
SpawnPoint=0,0,0

# I giocatori possono entrare ed uscire dal PVP su base individuale. Un giocatore può ferire un altro giocatore solo quando almeno uno di loro è in modalità PVP, come mostrato dal teschio non oscurato e dalle ossa incrociate sulla sinistra dello schermo. Quando SafetySystem=false, i giocatori sono liberi di ferirsi a vicenda in qualsiasi momento se il PVP è abilitato.
SafetySystem=true

# Visualizzare un'icona a forma di teschio sopra la testa dei giocatori che sono entrati in modalità PVP
ShowSafety=true

# Il tempo impegato a un giocatore per entrare o uscire dalla modalità PvP. Minimo=0 Massimo=1000 Predefinito=2
SafetyToggleTimer=2

# Il ritardo prima che un giocatore possa entrare o uscire di nuovo dalla modalità PVP, dopo averlo fatto di recente Minimo=0 Massimo=1000 Predefinito=3
SafetyCooldownTimer=3

# Minimo=0 Massimo=60 Predefinito=60
SafetyDisconnectDelay=60

# Categorie di oggetti con cui i nuovi giocatori cominciano la partita. Separa i diversi tipi con una virgola. Es: Base.Axe,Base.Bag_BigHikingBag
SpawnItems=

# Porta iniziale predefinita per i dati del giocatore. Se UDP, questa è una delle due porte utilizzate. Minimo=0 Massimo=65535 Predefinito=16261
DefaultPort=27006

# Minimo=0 Massimo=65535 Predefinito=16262
UDPPort=27007

# Il Reset ID determina se il server ha subito un soft-reset. Se questo numero corrisponde al client, il client deve creare un nuovo personaggio. Usato insieme a PlayerServerID. Si consiglia vivamente di salvare questi ID da qualche parte Minimo=0 Massimo=2147483647 Predefinito=917232598
ResetID=64608

# Scrivi qui l'ID della Mod. Lo puoi trovare in \Steam\steamapps\workshop\modID\mods\modName\info.txt
Mods=

# Scrivi il nome della cartella della Mod che trovi in \Steam\steamapps\workshop\modID\mods\modName\media\maps\
Map=Muldraugh, KY

# Espelli i Client i cui file di gioco non corrispondono a quelli del server.
DoLuaChecksum=true

DenyLoginOnOverloadedServer=true

# Mostra il server nel browser di gioco. (Nota: i server abilitati a Steam sono sempre visibili nel browser dei server Steam)
Public=false

# Nome del server visualizzato nel browser di gioco e, se applicabile, nel browser di Steam
PublicName=My PZ Server

# Descrizione visualizzata nel browser del server pubblico del gioco. Digitando   verrà creata una nuova riga nella tua descrizione
PublicDescription=

# Numero massimo di giocatori che possono essere sul server in una sola volta. Questo esclude gli amministratori.
# ATTENZIONE: Un numero di giocatori del server superiore a 32 può potenzialmente causare uno scarso funziona della mappa e desincronizzazione. Si prega di procedere con cautela. Minimo=1 Massimo=100 Predefinito=32
MaxPlayers=32

# Limite di ping millisecondi prima di venire espulsi dal server. Impostalo a 0 per disabilitarlo Minimo=0 Massimo=2147483647 Predefinito=0
PingLimit=0

# Items will not respawn in buildings that players have claimed as a safehouse
SafehousePreventsLootRespawn=true

# Rimuovere gli account dei giocatori dalla whitelist dopo la morte. Questo impedisce ai giocatori di creare un nuovo personaggio dopo la morte sui server Open=false
DropOffWhiteListAfterDeath=false

# Ogni forma di fiamma è disabilitata, tranne i fuochi da campo.
NoFire=false

# Se selezionata, ogni volta che un giocatore muore un messaggio globale sarà visualizzato nella chat
AnnounceDeath=false

# If checked, every time an animal dies a global message will be displayed in the chat
AnnounceAnimalDeath=false

# Le parti caricate della mappa vengono salvate dopo che questo numero impostato di minuti del mondo reale è passato. (La mappa viene solitamente salvata solo dopo che i clienti lasciano un'area caricata) Minimo=0 Massimo=2147483647 Predefinito=0
SaveWorldEveryMinutes=0

# Sia gli amministratori che i giocatori possono rivendicare i rifugi
PlayerSafehouse=false

# Solo gli Amministratori possono reclamare i rifugi.
AdminSafehouse=false

# Permettere ai non membri di entrare in un rifugio senza essere invitati
SafehouseAllowTrepass=true

# Permetti al fuoco di danneggiare i rifugi.
SafehouseAllowFire=true

# Permetti ai non membri di prendere oggetti dai rifugi.
SafehouseAllowLoot=true

# I giocatori iniziano in un rifugio di cui erano membri prima di morire.
SafehouseAllowRespawn=false

# I giocatori devono essere sopravvissuti a questo numero di giorni di gioco prima di poter reclamare un rifugio Minimo=0 Massimo=2147483647 Predefinito=0
SafehouseDaySurvivedToClaim=0

# I giocatori vengono automaticamente rimossi da un rifugio che non hanno visitato per così tante ore del mondo reale Minimo=0 Massimo=2147483647 Predefinito=144
SafeHouseRemovalTime=144

# Regola se i giocatori possono rivendicare edifici non residenziali.
SafehouseAllowNonResidential=false

SafehouseDisableDisguises=true

# Minimo=0 Massimo=2147483647 Predefinito=20000
MaxSafezoneSize=20000

# Permetti ai giocatori di distruggere gli oggetti del Mondo con il Martello da demolizione.
AllowDestructionBySledgehammer=true

# Permettere ai giocatori di distruggere gli oggetti del mondo solo nel loro rifugio (richiede AllowDestructionBySledgehammer su vero).
SledgehammerOnlyInSafehouse=false

War=true

# Time in seconds before the war starts. Minimo=60 Massimo=2147483647 Predefinito=600
WarStartDelay=600

# War duration in seconds. Minimo=60 Massimo=2147483647 Predefinito=3600
WarDuration=3600

# Safehouse hit points limit. Minimo=0 Massimo=2147483647 Predefinito=3
WarSafehouseHitPoints=3

# ServerPlayerID determina se un personaggio è di un altro server o di un giocatore singolo. Questo valore può essere modificato da soft reset. Se questo numero corrisponde al cliente, il cliente deve creare un nuovo personaggio. Questo è usato insieme a ResetID. Si consiglia vivamente di fare il backup di questi ID da qualche parte
ServerPlayerID=247253203

# La porta per l'RCON (Remote Console) Minimo=0 Massimo=65535 Predefinito=27015
RCONPort=27015

# Password RCON (Scegliere una password forte)
RCONPassword=

# Permette l'integrazione della chat di testo globale con un canale Discord
DiscordEnable=false

# Token di accesso al bot Discord
DiscordToken=

# The Discord chat channel name
DiscordChatChannel=

# The Discord logs channel name
DiscordLogChannel=

# The Discord commands channel name
DiscordCommandChannel=

# The Slack incoming webhook URL
WebhookAddress=

# I giocatori devono conoscere questa password per unirsi al server. (Ignorato quando si ospita un server tramite il pulsante Ospita.)
Password=

# Limita il numero di account che un utente Steam può creare su questo server. Viene ignorato quando ospiti un server Steam. Minimo=0 Massimo=2147483647 Predefinito=0
MaxAccountsPerUser=0

# Consentire i giocatori in coop/schermo condiviso
AllowCoop=true

# I giocatori possono dormire quando il loro sopravvissuto è stanco, ma non hanno bisogno di dormire
SleepAllowed=false

# I giocatori si stancano e hanno bisogno di dormire. (Ignorato se SleepAllowed=false)
SleepNeeded=false

# WIP: Activating this setting may cause visual desynchronization of player positions.
KnockedDownAllowed=false

SneakModeHideFromOtherPlayers=true

UltraSpeedDoesnotAffectToAnimals=false

# Elenca gli ID dei Mod delle officine che il server deve scaricare. Ognuno deve essere separato da un punto e virgola. Esempio: WorkshopItems=514427485;513111049
WorkshopItems=

# Mostra i nomi utente e gli avatar di Steam nella lista dei giocatori. Può essere true (visibile a tutti), false (visibile a nessuno), o admin (visibile solo agli amministratori)
SteamScoreboard=false

# Abilita il Sistema VAC di Steam.
SteamVAC=true

# Tenta di configurare un gateway internet abilitato UPnP per impostare automaticamente le regole di inoltro delle porte. Il server tornerà alle porte predefinite se questo non riesce
UPnP=true

# VOIP è abilitato quando è spuntato
VoiceEnable=true

# La distanza minima di tile su cui i suoni VOIP possono essere sentiti. Minimo=0,00 Massimo=100000,00 Predefinito=10,00
VoiceMinDistance=10.0

# La distanza massima di tile su cui i suoni VOIP possono essere sentiti. Minimo=0,00 Massimo=100000,00 Predefinito=100,00
VoiceMaxDistance=100.0

# Attiva/disattiva l'audio direzionale per VOIP
Voice3D=true

# Minimo=10,00 Massimo=150,00 Predefinito=70,00
SpeedLimit=70.0

LoginQueueEnabled=false

# Minimo=20 Massimo=1200 Predefinito=60
LoginQueueConnectTimeout=60

# Impostare l'IP da cui il server viene trasmesso. Questo è per le configurazioni di rete con indirizzi IP multipli, come le server farm
server_browser_announced_ip=

# I giocatori possono respawnare nel gioco alle coordinate in cui sono morti
PlayerRespawnWithSelf=false

# I giocatori possono respawnare nel gioco nella posizione di un giocatore a schermo diviso / gioco remoto
PlayerRespawnWithOther=false

# Regola la velocità con cui passa il tempo mentre i giocatori dormono. Il valore moltiplica la velocità del tempo che passa durante il sonno. Minimo=1,00 Massimo=100,00 Predefinito=40,00
FastForwardMultiplier=40.0

# La Casa sicura si comporta come una casa normale se un membro della Casa sicura è connesso (quindi sicura quando i giocatori sono offline)
DisableSafehouseWhenPlayerConnected=false

# I giocatori possono creare fazioni quando è vero
Faction=true

# I giocatori devono sopravvivere a questo numero di giorni di gioco prima di poter creare una fazione Minimo=0 Massimo=2147483647 Predefinito=0
FactionDaySurvivedToCreate=0

# Numero di giocatori richiesti come membri della fazione prima che il proprietario della fazione possa creare un tag di gruppo Minimo=1 Massimo=2147483647 Predefinito=1
FactionPlayersRequiredForTag=1

# Disabilita le trasmissioni radio dei giocatori con qualsiasi livello di accesso
DisableRadioStaff=false

# Disabilita le trasmissioni radio dai giocatori con livello di accesso 'admin'.
DisableRadioAdmin=true

# Trasmissioni radio disabilitate da giocatori con livello di accesso gm.
DisableRadioGM=true

# Disabilita le trasmissioni radio dai giocatori con livello di accesso 'sorvegliate'.
DisableRadioOverseer=false

# Disabilita le trasmissioni radio dai giocatori con livello di accesso 'moderatore'.
DisableRadioModerator=false

# Disattiva le trasmissioni radio dei giocatori invisibili
DisableRadioInvisible=true

# Elenco di comandi separati da punto e virgola che non verranno scritti nel registro del server cmd.txt.  -vehicle.*Significa non scrivere alcun comando del veicolo.  +vehicle.installPart significa scrivere quel comando.
ClientCommandFilter=-vehicle.*;+vehicle.damageWindow;+vehicle.fixPart;+vehicle.installPart;+vehicle.uninstallPart

# Elenco separato da punto e virgola delle azioni che saranno scritte nel log del server ClientActionLogs.txt.
ClientActionLogs=ISEnterVehicle;ISExitVehicle;ISTakeEngineParts;

# Traccia i cambiamenti nei livelli dei perk dei giocatori nel log del server PerkLog.txt
PerkLogs=true

# Numero massimo di oggetti che possono essere messi in un contenitore. Zero significa che non c'è limite. (NOTA BENE: questo include piccoli oggetti individuali come i chiodi. Un limite di 50 significa che solo 50 chiodi possono essere conservati). Minimo=0 Massimo=9000 Predefinito=0
ItemNumbersLimitPerContainer=0

# Numero di giorni prima che le vecchie macchie di sangue vengano rimosse.
# La rimozione avviene quando i pezzi di mappa vengono caricati.
# Zero significa che non scompariranno mai Minimo=0 Massimo=365 Predefinito=0
BloodSplatLifespanDays=0

# Permettere l'uso di caratteri non ASCII (cirillici ecc.) nei nomi utente
AllowNonAsciiUsername=false

BanKickGlobalSound=true

# Se è attivo, quando si attiva l'ora per la rimozione dei cadaveri, rimuoverà anche i cadaveri dei giocatori dal terreno.
RemovePlayerCorpsesOnCorpseRemoval=false

# Se è vero, il giocatore può utilizzare il pulsante Elimina tutto sui bidoni.
TrashDeleteAll=false

# Se è vero, il giocatore può colpire di nuovo quando viene colpito da un altro giocatore.
PVPMeleeWhileHitReaction=false

# Se vero, i giocatori dovranno mettere il mouse sopra qualcuno per vedere il loro nome di visualizzazione.
MouseOverToSeeDisplayName=true

# Se è vero, nascondi automaticamente il giocatore che non puoi vedere (come gli zombie).
HidePlayersBehindYou=true

# Moltiplicatore dei danni per gli attacchi in mischia PVP. Minimo=0,00 Massimo=500,00 Predefinito=30,00
PVPMeleeDamageModifier=30.0

# Moltiplicatore dei danni per gli attacchi a distanza PVP. Minimo=0,00 Massimo=500,00 Predefinito=50,00
PVPFirearmDamageModifier=50.0

# Modificare la gamma di attrazione degli zombie verso le auto. (Valori più bassi possono aiutare con il ritardo). Minimo=0,00 Massimo=10,00 Predefinito=0,50
CarEngineAttractionModifier=0.5

# Regola se i giocatori urtano (e rovesciano) altri giocatori quando li attraversano.
PlayerBumpPlayer=false

# Controlla la visualizzazione dei giocatori remoti sulla mappa del gioco. 1=Nascosto 2=Amici 3=Tutti Minimo=1 Massimo=4 Predefinito=1
MapRemotePlayerVisibility=1

# Minimo=1 Massimo=300 Predefinito=5
BackupsCount=5

BackupsOnStart=true

BackupsOnVersionChange=true

# Minimo=0 Massimo=1500 Predefinito=0
BackupsPeriod=0

# Disables vehicle towing
DisableVehicleTowing=false

# Disables trailer towing
DisableTrailerTowing=false

# Disables burnt vehicle towing
DisableBurntTowing=false

# Path to the file with the list of words to be prohibited. Each word must be on a separate line
BadWordListFile=

# Path to the file with the list of words that should be allowed, even if they contain bad word. Each word should be on a separate line.
GoodWordListFile=

# What to do with the sender of a bad word in the chat: 1 - ban, 2 - kick, 3 - record the violation in the database, 4 - mute
BadWordPolicy=3

# The symbol or piece of text that will replace the bad word
BadWordReplacement=[HIDDEN]

# Disables safety system anti-cheat protection.
AntiCheatSafety=4

AntiCheatMovement=4

# Disables character hit anti-cheat protection.
AntiCheatHit=4

# Disables packet checks anti-cheat protection.
AntiCheatPacket=4

# Disables player permissions anti-cheat protection.
AntiCheatPermission=4

# Disables player XP anti-cheat protection.
AntiCheatXP=4

# Disables fire checks anti-cheat protection.
AntiCheatFire=4

# Disables safehouse anti-cheat protection.
AntiCheatSafeHouse=4

# Disables recipe checks anti-cheat protection.
AntiCheatRecipe=4

AntiCheatPlayer=4

# Disables checksum anti-cheat protection.
AntiCheatChecksum=4

# Disables item checks anti-cheat protection.
AntiCheatItem=4

AntiCheatServerCustomization=4

# Sets the multiplayer update period in seconds. Statistics is disabled if value is 0. Minimo=0 Massimo=10 Predefinito=1
MultiplayerStatisticsPeriod=1

# Disables scoreboard.
DisableScoreboard=false

# Hides admins in the player list.
HideAdminsInPlayerList=false

# Minimo=100 Massimo=1000 Predefinito=300
MaxPacketsPerSecond=300

# The worldgen seed used to generate the world.
# If you want to change this, put a new value in and delete map_worldgen.bin in your save directory.
Seed=FyqhBDLNpSPLknRQ

UsePhysicsHitReaction=false

# Minimo=64 Massimo=1024 Predefinito=200
ChatMessageCharacterLimit=200

# Minimo=1 Massimo=30 Predefinito=3
ChatMessageSlowModeTime=3